name: faceid
description: "FaceID Attendance Demo"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  camera: ^0.11.0
  dio: ^5.4.3
  shared_preferences: ^2.3.3
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.1.3
  http: ^1.6.0
  intl: ^0.19.0
  provider: ^6.1.2
  geolocator: ^13.0.1
  path_provider: ^2.1.3
  equatable: ^2.0.5
  image: ^4.1.7
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
